#
# Made with ❤️ and adobo by Kurocado Studio
# Copyright (c) 2024. All Rights Reserved.
#
# Learn more about Kurocado Studio: {@link https://www.kurocado.studio}
#
# Explore our open-source projects: {@link https://github.com/kurocado-studio}
#

name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    uses: kurocado-studio/styleguide/.github/workflows/workflow.lint.yml@main
    secrets: inherit

  test:
    needs: lint
    uses: kurocado-studio/styleguide/.github/workflows/workflow.test.yml@main
    secrets: inherit

  document:
    needs: test
    uses: kurocado-studio/styleguide/.github/workflows/workflow.document.yml@main
    secrets: inherit

  release:
    needs: document
    uses: kurocado-studio/styleguide/.github/workflows/workflow.release.yml@main
    secrets: inherit
    with:
      branch_name: ${{ github.ref }}

  deploy:
    needs: release
    uses: kurocado-studio/styleguide/.github/workflows/workflow.deploy.yml@main
    secrets: inherit
    with:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
